# Generated by Django 4.2.1 on 2023-05-12 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApartCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApartPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LcdOrSingle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mebel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfApart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vidovaya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Apart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=10, max_digits=20)),
                ('image', models.ImageField(upload_to='products_images')),
                ('yearOfBuild', models.DateField()),
                ('quantityRoom', models.PositiveIntegerField(default=1)),
                ('buildingAge', models.PositiveIntegerField(default=1)),
                ('developer', models.CharField(max_length=256)),
                ('quantityOfMetres', models.PositiveIntegerField(default=1)),
                ('infostracture', models.CharField(max_length=128, unique=True)),
                ('qauntityOfFloors', models.PositiveIntegerField(default=1)),
                ('apartmentNumber', models.PositiveIntegerField(default=1)),
                ('quantityOfBathroom', models.PositiveIntegerField(default=1)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.apartcategory')),
            ],
        ),
    ]
