# Generated by Django 4.2.1 on 2023-05-13 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_apart_typeofapart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apart',
            name='typeOfApart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='products.typeofapart'),
        ),
    ]
