# Generated by Django 4.2.1 on 2023-05-17 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_apart_yearofbuild'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apart',
            old_name='yearOfBuild',
            new_name='DateOfBuild',
        ),
    ]
