# Generated by Django 4.2.1 on 2023-05-13 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_apart_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='apart',
            name='typeOfApart',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='products.typeofapart'),
        ),
    ]
