# Generated by Django 4.2.1 on 2023-05-13 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_apart_typeofapart'),
    ]

    operations = [
        migrations.AddField(
            model_name='apart',
            name='LcdOrS',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='products.lcdorsingle'),
        ),
        migrations.AddField(
            model_name='apart',
            name='apartPlan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='products.apartplan'),
        ),
        migrations.AddField(
            model_name='apart',
            name='mebel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='products.mebel'),
        ),
        migrations.AddField(
            model_name='apart',
            name='vidovaya',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='products.vidovaya'),
        ),
    ]
