# Generated by Django 4.2.1 on 2023-05-14 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_quantityroom_alter_apart_quantityroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apart',
            name='quantityRoom',
            field=models.CharField(default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='apart',
            name='yearOfBuild',
            field=models.PositiveIntegerField(),
        ),
        migrations.DeleteModel(
            name='QuantityRoom',
        ),
    ]
