# Generated by Django 4.2.1 on 2023-05-14 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_apart_quantityroom_alter_apart_yearofbuild_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apart',
            name='yearOfBuild',
            field=models.DateField(),
        ),
    ]
