# Generated by Django 4.2.1 on 2023-05-18 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_apart_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='apart',
            name='dealType',
            field=models.TextField(default='Satilk'),
        ),
        migrations.AddField(
            model_name='apart',
            name='floorNumber',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='apart',
            name='livingSpace',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='apart',
            name='location',
            field=models.TextField(default='Mersin/'),
        ),
    ]
