# Generated by Django 4.2.1 on 2023-05-18 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_apart_dealtype_apart_floornumber_apart_livingspace_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apart',
            name='Tovarimage1',
            field=models.ImageField(null=True, upload_to='products_images'),
        ),
        migrations.AddField(
            model_name='apart',
            name='Tovarimage2',
            field=models.ImageField(null=True, upload_to='products_images'),
        ),
        migrations.AddField(
            model_name='apart',
            name='Tovarimage3',
            field=models.ImageField(null=True, upload_to='products_images'),
        ),
    ]
