# Generated by Django 4.2.1 on 2023-06-23 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_apart_tovarimage1_apart_tovarimage2_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apart',
            options={'verbose_name': 'Недвижимость', 'verbose_name_plural': 'Недвижимость'},
        ),
        migrations.AlterModelOptions(
            name='apartcategory',
            options={'verbose_name': 'Категория недвижимости', 'verbose_name_plural': 'Категории недвижимости'},
        ),
        migrations.AlterModelOptions(
            name='apartplan',
            options={'verbose_name': 'Планировка недвижимости', 'verbose_name_plural': 'Планировки недвижимости'},
        ),
        migrations.AlterModelOptions(
            name='lcdorsingle',
            options={'verbose_name': 'ЖК или одиночное здание', 'verbose_name_plural': 'ЖК или одиночные здания'},
        ),
        migrations.AlterModelOptions(
            name='mebel',
            options={'verbose_name': 'Мебель', 'verbose_name_plural': 'Мебель'},
        ),
        migrations.AlterModelOptions(
            name='typeofapart',
            options={'verbose_name': 'Тип недвижимости', 'verbose_name_plural': 'Типы недвижимости'},
        ),
        migrations.AlterModelOptions(
            name='vidovaya',
            options={'verbose_name': 'Видовая характеристика', 'verbose_name_plural': 'Видовые характеристики'},
        ),
        migrations.AlterField(
            model_name='apart',
            name='DateOfBuild',
            field=models.DateField(verbose_name='Дата постройки'),
        ),
        migrations.AlterField(
            model_name='apart',
            name='LcdOrS',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='products.lcdorsingle', verbose_name='ЖК или одиночное здание'),
        ),
        migrations.AlterField(
            model_name='apart',
            name='Tovarimage1',
            field=models.ImageField(null=True, upload_to='products_images', verbose_name='Изображение товара 1'),
        ),
        migrations.AlterField(
            model_name='apart',
            name='Tovarimage2',
            field=models.ImageField(null=True, upload_to='products_images', verbose_name='Изображение товара 2'),
        ),
        migrations.AlterField(
            model_name='apart',
            name='Tovarimage3',
            field=models.ImageField(null=True, upload_to='products_images', verbose_name='Изображение товара 3'),
        ),
        migrations.AlterField(
            model_name='apart',
            name='apartPlan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='products.apartplan', verbose_name='Планировка недвижимости'),
        ),
        migrations.AlterField(
            model_name='apart',
            name='apartmentNumber',
            field=models.PositiveIntegerField(default=1, verbose_name='Номер квартиры'),
        ),
        migrations.AlterField(
            model_name='apart',
            name='buildingAge',
            field=models.PositiveIntegerField(default=1, verbose_name='Возраст здания'),
        ),
        migrations.AlterField(
            model_name='apart',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='products.apartcategory', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='apart',
            name='city',
            field=models.TextField(default='city', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='apart',
            name='dealType',
            field=models.TextField(default='Satilk', verbose_name='Тип сделки'),
        ),
        migrations.AlterField(
            model_name='apart',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='apart',
            name='developer',
            field=models.CharField(max_length=256, verbose_name='Застройщик'),
        ),
        migrations.AlterField(
            model_name='apart',
            name='floorNumber',
            field=models.PositiveIntegerField(default=1, verbose_name='Номер этажа'),
        ),
        migrations.AlterField(
            model_name='apart',
            name='image',
            field=models.ImageField(upload_to='products_images', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='apart',
            name='infostracture',
            field=models.CharField(max_length=128, unique=True, verbose_name='Инфраструктура'),
        ),
        migrations.AlterField(
            model_name='apart',
            name='livingSpace',
            field=models.PositiveIntegerField(default=1, verbose_name='Жилая площадь'),
        ),
        migrations.AlterField(
            model_name='apart',
            name='location',
            field=models.TextField(default='Mersin/', verbose_name='Местоположение'),
        ),
        migrations.AlterField(
            model_name='apart',
            name='mebel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='products.mebel', verbose_name='Мебель'),
        ),
        migrations.AlterField(
            model_name='apart',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='apart',
            name='price',
            field=models.FloatField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='apart',
            name='qauntityOfFloors',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество этажей'),
        ),
        migrations.AlterField(
            model_name='apart',
            name='quantityOfBathroom',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество ванных комнат'),
        ),
        migrations.AlterField(
            model_name='apart',
            name='quantityOfMetres',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество квадратных метров'),
        ),
        migrations.AlterField(
            model_name='apart',
            name='quantityRoom',
            field=models.CharField(default='1', max_length=10, verbose_name='Количество комнат'),
        ),
        migrations.AlterField(
            model_name='apart',
            name='typeOfApart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='products.typeofapart', verbose_name='Тип недвижимости'),
        ),
        migrations.AlterField(
            model_name='apart',
            name='vidovaya',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='products.vidovaya', verbose_name='Видовая характеристика'),
        ),
    ]
