# Generated by Django 4.2 on 2023-07-25 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_apart_options_alter_apartcategory_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apart',
            name='Tovarimage1',
        ),
        migrations.RemoveField(
            model_name='apart',
            name='Tovarimage2',
        ),
        migrations.RemoveField(
            model_name='apart',
            name='Tovarimage3',
        ),
        migrations.CreateModel(
            name='ApartmentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products_images', verbose_name='Изображение')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.apart', verbose_name='Квартира')),
            ],
            options={
                'verbose_name': 'Изображение квартиры',
                'verbose_name_plural': 'Изображения квартир',
            },
        ),
    ]
